-- CRIANDO TABELA DEPARTAMENTO
	CREATE TABLE DEP
	(
		COD_DEPTO	INT  IDENTITY NOT NULL,
		DEPTO		VARCHAR(10)
		
		CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY (COD_DEPTO)	
	);

-- CRINDO TABELA CARGO
	CREATE TABLE CAR
	(
		COD_CARGO		INT IDENTITY NOT NULL,
		CARGO			VARCHAR (30),
		SALARIO_INIC	INT

		CONSTRAINT PK_CARGO PRIMARY KEY (COD_CARGO)

	);

--CRIANDO TABELA EMPREGADOS
	CREATE TABLE EMPREGADOS
	(
		COD_FUN			INT IDENTITY NOT NULL,
		NOME			VARCHAR (20) NOT NULL,
		NUM_DEPEND		TINYINT,
		DATA_NASC		DATETIME,
		COD_DEPTO		INT NOT NULL,
		COD_CARGO		INT NOT NULL,
		DATA_ADMSS		DATETIME,
		SALARIO			INT,
		SINDIC			BIT,
		OBS				CHAR

		CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (COD_FUN),
		CONSTRAINT FK_DEPARTAMENTO FOREIGN KEY (COD_DEPTO)
		REFERENCES DEP (COD_DEPTO),
		CONSTRAINT FK_CARGO FOREIGN KEY (COD_CARGO)
		REFERENCES CAR (COD_CARGO)

	);

--CRIANDO TABELA




 